# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BmobDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'BmobSDK', '~> 2.2.3'
  # Pods for BmobDemo

  target 'BmobDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BmobDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
